# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            avjaarsveld
tagline:          'to #{1.0/0.0} and beyond!'
url:              http://avjaarsveld.github.io
paginate:         10
baseurl:          /
author:
  name:           Albert Van-Jaarsveld
  url:            http://avjaarsveld.github.io/about
  email:          asvj3@hotmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Syntax Highliting
markdown:         redcarpet
